using System;

namespace StorageService.Exceptions
{
	internal sealed class BattleNotFinishedException : Exception
	{
		
	}
}